server:
  port: 7075

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587  #default portu bu smtp'nin
    username: ${java9mail}
    password: ${java9mailpassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbitmq:
    mail-queue: mailQueue
